---
deployment:
  tasks:
    # Instalar dependencias
    - export DEPLOYPATH=/home/otfidqlcuq/tools.cambiodigital.net
    - /bin/cp -R * $DEPLOYPATH
    # Instalar dependencias de Node.js
    - cd $DEPLOYPATH && /usr/bin/npm install
    # Construir el proyecto
    - cd $DEPLOYPATH && /usr/bin/npm run build
